services:
  - type: web
    name: pdf-powerhouse
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/health/
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
