# Generated by Django 5.2.16 on 2026-07-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
