# Generated by Django 5.2.16 on 2026-07-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscriptionplan_webhooklog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
