# Generated by Django 5.2.16 on 2026-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_downloadhistory_user_alter_processedfile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolusagelog',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
